importation des bibliotheques

In [ ]:
import pandas as pd
import numpy as np 
import matplotlib as plt

ModuleNotFoundError: No module named 'pandas'

In [ ]:
#chargement du fichier
df = pd.read_csv("data/DataCoSupplyChainDataset.csv", encoding="latin-1")

In [3]:
#taille 
df.shape

(180519, 53)

In [4]:
#les premieres lignes
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

PREPROCESSING

In [5]:
#verifier les types des donnees
df.dtypes

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Email                    object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Password                 object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                 float64
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
order date (DateOrders)           object
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                     object
Product Name                      object
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

Les deux colonnes de dates sont enregistrées comme du texte . Les deux codes postaux, Customer Zipcode et Order Zipcode, apparaissent avec une virgule alors que ce sont des nombres entiers. Enfin, Product Description est interprétée comme une colonne numérique alors qu’elle devrait contenir du texte. Je vérifierai d’abord les valeurs manquantes dans ces colonnes afin de déterminer les corrections à apporter et les données à supprimer si nécessaire.

In [6]:
#valeurs manquantes
df.isna().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [7]:
pourcentage_manquant = (df.isnull().sum() / len(df)) * 100

In [8]:
pourcentage_manquant

Type                               0.000000
Days for shipping (real)           0.000000
Days for shipment (scheduled)      0.000000
Benefit per order                  0.000000
Sales per customer                 0.000000
Delivery Status                    0.000000
Late_delivery_risk                 0.000000
Category Id                        0.000000
Category Name                      0.000000
Customer City                      0.000000
Customer Country                   0.000000
Customer Email                     0.000000
Customer Fname                     0.000000
Customer Id                        0.000000
Customer Lname                     0.004432
Customer Password                  0.000000
Customer Segment                   0.000000
Customer State                     0.000000
Customer Street                    0.000000
Customer Zipcode                   0.001662
Department Id                      0.000000
Department Name                    0.000000
Latitude                           0.000000
Longitude                          0.000000
Market                             0.000000
Order City                         0.000000
Order Country                      0.000000
Order Customer Id                  0.000000
order date (DateOrders)            0.000000
Order Id                           0.000000
Order Item Cardprod Id             0.000000
Order Item Discount                0.000000
Order Item Discount Rate           0.000000
Order Item Id                      0.000000
Order Item Product Price           0.000000
Order Item Profit Ratio            0.000000
Order Item Quantity                0.000000
Sales                              0.000000
Order Item Total                   0.000000
Order Profit Per Order             0.000000
Order Region                       0.000000
Order State                        0.000000
Order Status                       0.000000
Order Zipcode                     86.239676
Product Card Id                    0.000000
Product Category Id                0.000000
Product Description              100.000000
Product Image                      0.000000
Product Name                       0.000000
Product Price                      0.000000
Product Status                     0.000000
shipping date (DateOrders)         0.000000
Shipping Mode                      0.000000
dtype: float64

In [9]:
# pourcentage de valeurs manquantes par colonne
pourcentage_manquant = (df.isnull().sum() / len(df)) * 100

In [10]:
pourcentage_manquant

Type                               0.000000
Days for shipping (real)           0.000000
Days for shipment (scheduled)      0.000000
Benefit per order                  0.000000
Sales per customer                 0.000000
Delivery Status                    0.000000
Late_delivery_risk                 0.000000
Category Id                        0.000000
Category Name                      0.000000
Customer City                      0.000000
Customer Country                   0.000000
Customer Email                     0.000000
Customer Fname                     0.000000
Customer Id                        0.000000
Customer Lname                     0.004432
Customer Password                  0.000000
Customer Segment                   0.000000
Customer State                     0.000000
Customer Street                    0.000000
Customer Zipcode                   0.001662
Department Id                      0.000000
Department Name                    0.000000
Latitude                           0.000000
Longitude                          0.000000
Market                             0.000000
Order City                         0.000000
Order Country                      0.000000
Order Customer Id                  0.000000
order date (DateOrders)            0.000000
Order Id                           0.000000
Order Item Cardprod Id             0.000000
Order Item Discount                0.000000
Order Item Discount Rate           0.000000
Order Item Id                      0.000000
Order Item Product Price           0.000000
Order Item Profit Ratio            0.000000
Order Item Quantity                0.000000
Sales                              0.000000
Order Item Total                   0.000000
Order Profit Per Order             0.000000
Order Region                       0.000000
Order State                        0.000000
Order Status                       0.000000
Order Zipcode                     86.239676
Product Card Id                    0.000000
Product Category Id                0.000000
Product Description              100.000000
Product Image                      0.000000
Product Name                       0.000000
Product Price                      0.000000
Product Status                     0.000000
shipping date (DateOrders)         0.000000
Shipping Mode                      0.000000
dtype: float64

In [11]:

# Afficher uniquement les colonnes contenant des valeurs manquantes
print(pourcentage_manquant[pourcentage_manquant > 0])

Customer Lname           0.004432
Customer Zipcode         0.001662
Order Zipcode           86.239676
Product Description    100.000000
dtype: float64

dans le dataset, 4 colonnes presentes des valeurs manquantes
Valeurs manquantes : Product Description est entièrement vide, tandis que Order Zipcode ne contient que 24 840 valeurs renseignées sur 180 519.

In [12]:
#les doublons
df.duplicated().sum()

np.int64(0)

le dataset ne contient aucun doublon

In [13]:
#statisqtiques descriptives
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

Délais de livraison : en moyenne, les commandes prennent 3,50 jours à être expédiées, contre 2,93 jours prévus. Environ 54,8 % des commandes présentent un risque de retard.
Bénéfices : le bénéfice moyen est de 21,97, mais certaines commandes enregistrent des pertes importantes, jusqu’à −4 274,98. 

La colonne statut_produit indique la disponibilité du produit : 1 pour indisponible, 0 pour disponible. Son minimum et son maximum valent tous deux 0, et son écart-type est nul : elle prend donc la même valeur sur les 180 519 lignes. Une colonne constante ne permet aucune distinction entre les lignes et n’apporte aucune information à l’analyse ; je la supprime. Cela signifie aussi que ce jeu de données ne contient aucune rupture de stock enregistrée, et que cet aspect ne pourra pas être étudié.
Autres variables : les quantités varient de 1 à 5 et les ventes sont positives, sans anomalie évidente à première vue.

In [14]:
# statut de livraison (Nombre de lignes en retard, en avance, à l’heure, annulées)
df["Delivery Status"].value_counts()

Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

La répartition des commandes selon leur statut montre que les retards sont assez fréquents. Sur les 180 519 commandes, 98 977 ont été livrées en retard, soit environ 54,83 %. À l’inverse, 41 592 commandes ont été expédiées en avance (23,04 %), tandis que 32 196 ont été livrées dans les délais prévus (17,83 %). Enfin, 7 754 commandes ont été annulées lors de l’expédition, soit environ 4,29 %

In [15]:
#Nombre de lignes par mode d’expédition
df["Shipping Mode"].value_counts()

Shipping Mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

Le mode d’expédition le plus utilisé est Standard Class, avec 107 752 commandes, soit environ 59,69 % du total. Il est suivi de Second Class avec 35 216 commandes (19,51 %), puis de First Class avec 27 814 commandes (15,41 %). Enfin, Same Day est le moins utilisé, avec 9 737 commandes (5,39 %).

In [16]:
#nombre de lignes par statuts de commande
df["Order Status"].value_counts()

Order Status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: count, dtype: int64

Le statut le plus fréquent est COMPLETE, avec 59 491 commandes, soit environ 32,95 % du total. Il est suivi de PENDING_PAYMENT (22,06 %) et de PROCESSING (12,13 %). Les commandes PENDING représentent 11,20 %, tandis que CLOSED en compte 10,87 %.
Les autres statuts sont moins fréquents, notamment ON_HOLD (5,43 %), SUSPECTED_FRAUD (2,25 %), CANCELED (2,04 %) et PAYMENT_REVIEW (1,05 %).

In [17]:
df["Product Status"].value_counts()

Product Status
0    180519
Name: count, dtype: int64

NETOYAGE DES DONNEES

In [18]:
#renommage des colones
NOMS = {
    "Type": "type_paiement",
    "Days for shipping (real)": "jours_reels",
    "Days for shipment (scheduled)": "jours_prevus",
    "Benefit per order": "benefice_commande",
    "Sales per customer": "ventes_par_client",
    "Delivery Status": "statut_livraison",
    "Late_delivery_risk": "risque_retard",
    "Category Id": "categorie_id",
    "Category Name": "categorie",
    "Customer City": "ville_client",
    "Customer Country": "pays_client",
    "Customer Email": "email_client",
    "Customer Fname": "prenom_client",
    "Customer Id": "client_id",
    "Customer Lname": "nom_client",
    "Customer Password": "mot_de_passe_client",
    "Customer Segment": "segment_client",
    "Customer State": "etat_client",
    "Customer Street": "rue_client",
    "Customer Zipcode": "code_postal_client",
    "Department Id": "departement_id",
    "Department Name": "departement",
    "Latitude": "latitude",
    "Longitude": "longitude",
    "Market": "marche",
    "Order City": "ville_livraison",
    "Order Country": "pays_livraison",
    "Order Customer Id": "commande_client_id",
    "order date (DateOrders)": "date_commande",
    "Order Id": "commande_id",
    "Order Item Cardprod Id": "ligne_produit_id",
    "Order Item Discount": "remise",
    "Order Item Discount Rate": "taux_remise",
    "Order Item Id": "ligne_id",
    "Order Item Product Price": "prix_unitaire",
    "Order Item Profit Ratio": "taux_marge",
    "Order Item Quantity": "quantite",
    "Sales": "ventes",
    "Order Item Total": "total_ligne",
    "Order Profit Per Order": "profit",
    "Order Region": "region_livraison",
    "Order State": "etat_livraison",
    "Order Status": "statut_commande",
    "Order Zipcode": "code_postal_livraison",
    "Product Card Id": "produit_id",
    "Product Category Id": "produit_categorie_id",
    "Product Description": "description_produit",
    "Product Image": "image_produit",
    "Product Name": "produit",
    "Product Price": "prix_produit",
    "Product Status": "statut_produit",
    "shipping date (DateOrders)": "date_expedition",
    "Shipping Mode": "mode_expedition",
}

df.columns = df.columns.str.strip()   #  poure enlèver les espaces cachés autour des noms

In [19]:
df_c= df.rename(columns=NOMS)

In [20]:
#suppression des colonnes inutiles
colonnes_inutiles = [
    "description_produit",    #  à 100 % de valeurs manquantes
    "code_postal_livraison",  # a 86,2 % de valeurs manquantes
    "email_client",           # masquée , car les email et les motes de passes des client st toujours masqués lors du remplissage des formulaire pour plus de confidentialité
    "mot_de_passe_client",    # masquée
    "statut_produit",         # toujours égale à 0
]
data = df_c.drop(columns=colonnes_inutiles)
print(df.shape)

(180519, 53)

In [21]:
# suppression des colonnes redondantes
paires = [
    ("profit", "benefice_commande"),
    ("total_ligne", "ventes_par_client"),
    ("produit_categorie_id", "categorie_id"),
    ("client_id", "commande_client_id"),
    ("produit_id", "ligne_produit_id"),
    ("prix_produit", "prix_unitaire"),
]

for copie, original in paires:
    if copie not in data.columns or original not in data.columns:
        print(f"{copie} / {original} : colonne absente, paire ignorée")
    elif (data[copie] == data[original]).all():
        data = data.drop(columns=copie)
        print(f"{copie} = {original} : identiques, copie supprimée")
    else:
        nb = (data[copie] != data[original]).sum()
        print(f"{copie} et {original} : {nb} lignes différentes, colonne conservée")

print(data.shape)

profit = benefice_commande : identiques, copie supprimée
total_ligne = ventes_par_client : identiques, copie supprimée
produit_categorie_id = categorie_id : identiques, copie supprimée
client_id = commande_client_id : identiques, copie supprimée
produit_id = ligne_produit_id : identiques, copie supprimée
prix_produit = prix_unitaire : identiques, copie supprimée
(180519, 42)

J’ai comparé ligne par ligne six paires de colonnes soupçonnées d’être redondantes d’après leurs noms et leurs statistiques. Les six paires se sont révélées strictement identiques sur les 180 519 lignes : benefice_commande et profit, ventes_par_client et total_ligne, categorie_id et produit_categorie_id, commande_client_id et client_id, ligne_produit_id et produit_id, prix_unitaire et prix_produit. Dans chaque cas, je n’ai conservé qu’une des deux colonnes, la seconde n’apportant aucune information supplémentaire. Cette redondance vient probablement de la fusion de plusieurs tables dans le fichier d’origine. Au total, le jeu de données passe de 53 à 42 colonnes, soit 11 colonnes supprimées, sans aucune perte d’information et sans modification du nombre de lignes

In [22]:
#conversion des dates en types dates
for col in ["date_commande", "date_expedition"]:
    data[col] = pd.to_datetime(data[col], format="%m/%d/%Y %H:%M", errors="coerce")

print(data[["date_commande", "date_expedition"]].dtypes)
print(data[["date_commande", "date_expedition"]].isna().sum())
print(data["date_commande"].min(), "->", data["date_commande"].max())

date_commande      datetime64[ns]
date_expedition    datetime64[ns]
dtype: object
date_commande      0
date_expedition    0
dtype: int64
2015-01-01 00:00:00 -> 2018-01-31 23:38:00

In [23]:
#nettoyons les texte: suppression des espaces au début et à la fin, et réduction des espaces doubles à un seul.

# Sélectionner les colonnes textuelles, sauf les dates
colonnes_texte = [
    col for col in data.select_dtypes(include=["object", "string"]).columns #repère automatiquement les colonnes de texte ; Les deux dates sont exclues, car elles ne sont pas du texte à nettoyer.
    if col not in ["date_commande", "date_expedition"]
]

print(f"{len(colonnes_texte)} colonnes textuelles à nettoyer.")

20 colonnes textuelles à nettoyer.

In [24]:
# Nettoyer les espaces dans chaque colonne
for col in colonnes_texte:
    anciennes_valeurs = data[col].copy()

    data[col] = data[col].str.strip().str.replace(r"\s+", " ", regex=True) #.str.strip() enlève les espaces au début et à la fin , .str.replace(r"\s+", " ", regex=True) remplace plusieurs espaces à la suite par un seul.

    # Compter les valeurs qui ont été modifiées
    nb_corrigees = (
        (anciennes_valeurs != data[col]) & anciennes_valeurs.notna()
    ).sum()

    if nb_corrigees > 0:
        print(f"{col} : {nb_corrigees} valeurs corrigées")

print("Nettoyage des textes terminé.")

categorie : 1543 valeurs corrigées
rue_client : 3036 valeurs corrigées
departement : 362 valeurs corrigées
region_livraison : 17925 valeurs corrigées
image_produit : 886 valeurs corrigées
produit : 1774 valeurs corrigées
Nettoyage des textes terminé.

Le nettoyage des textes a porté sur les 20 colonnes textuelles : suppression des espaces en début et en fin de valeur, et réduction des espaces multiples à un seul. Au total, 25 526 valeurs ont été corrigées dans 6 colonnes, les 14 autres étant déjà propres. La colonne la plus touchée est region_livraison, avec 17 925 valeurs corrigées, soit près de 10 % des lignes ; viennent ensuite rue_client (3 036), produit (1 774), categorie (1 543), image_produit (886) et departement (362). Ces défauts sont invisibles à l’œil nu mais lourds de conséquences : pour un ordinateur, deux libellés qui ne diffèrent que par un espace sont deux catégories distinctes. Sans cette correction, les regroupements par région, par catégorie ou par produit auraient donné des totaux fragmentés, et l’analyse des causes de retard en aurait été faussée

In [25]:
for col in colonnes_texte:
    n1 = data[col].nunique()
    n2 = data[col].str.lower().nunique()
    if n1 != n2:
        print(f"{col} : {n1} valeurs distinctes, mais {n2} sans tenir compte des majuscules")
print("Contrôle terminé")

prenom_client : 782 valeurs distinctes, mais 781 sans tenir compte des majuscules
Contrôle terminé

In [26]:
#traitemant des valeurs manquantes
manquants = data.isna().sum()
print(manquants[manquants > 0])

nom_client            8
code_postal_client    3
dtype: int64

In [27]:
data[data["code_postal_client"].isna()][["ville_client", "etat_client", "pays_client"]]

      ville_client etat_client pays_client
35704           CA       95758     EE. UU.
46440           CA       95758     EE. UU.
82511           CA       91732     EE. UU.

In [28]:
data["nom_client"] = data["nom_client"].fillna("Inconnu")
data["code_postal_client"] = data["code_postal_client"].fillna(0).astype(int)

In [29]:
print("Valeurs manquantes restantes :", data.isna().sum().sum())
print("Type du code postal :", data["code_postal_client"].dtype)
print(data.shape)

Valeurs manquantes restantes : 0
Type du code postal : int64
(180519, 42)

Je n’ai pas eu recours à la médiane ni au mode, méthodes habituelles d’imputation, car elles ne s’appliquent qu’aux quantités et aux catégories. Les deux colonnes concernées sont d’une autre nature : le code postal est un identifiant géographique et le nom une donnée propre à chaque personne. Leur attribuer la valeur la plus fréquente aurait créé des informations fausses, par exemple en rattachant des clients californiens au code postal majoritaire du fichier. »

Il reste à corriger le décalage : envoyez-moi le tableau du bloc précédent, celui qui affiche rue_client et les colonnes voisines.

In [30]:
#controle de coherence

regles = {
    "date de commande invalide": data["date_commande"].isna(), #Une commande sans date ne peut être ni située dans le temps ni mesurée
    "date d'expédition invalide": data["date_expedition"].isna(),
    "expédition antérieure à la commande": data["date_expedition"] < data["date_commande"], #On ne peut pas expédier un article avant qu’il soit commandé
    "quantité nulle ou négative": data["quantite"] <= 0,
    "vente négative": data["ventes"] < 0,
    "remise négative ou supérieure à la vente": (data["remise"] < 0) | (data["remise"] > data["ventes"]),
    "délai négatif": (data["jours_reels"] < 0) | (data["jours_prevus"] < 0),
    "risque de retard différent de 0 ou 1": ~data["risque_retard"].isin([0, 1]),
}

data["motif_rejet"] = ""
for motif, masque in regles.items():
    print(f"{motif:<45} : {masque.sum()} ligne(s)")
    data.loc[masque & (data["motif_rejet"] == ""), "motif_rejet"] = motif

rejets = data[data["motif_rejet"] != ""].copy()
data = data[data["motif_rejet"] == ""].drop(columns="motif_rejet").copy()

print()
print("Lignes rejetées  :", len(rejets))
print("Lignes conservées :", len(data))

date de commande invalide                     : 0 ligne(s)
date d'expédition invalide                    : 0 ligne(s)
expédition antérieure à la commande           : 0 ligne(s)
quantité nulle ou négative                    : 0 ligne(s)
vente négative                                : 0 ligne(s)
remise négative ou supérieure à la vente      : 0 ligne(s)
délai négatif                                 : 0 ligne(s)
risque de retard différent de 0 ou 1          : 0 ligne(s)

Lignes rejetées  : 0
Lignes conservées : 180519

J’ai soumis les 180 519 lignes à huit contrôles de cohérence, chacun correspondant à une situation impossible dans la réalité : date invalide, expédition antérieure à la commande, quantité nulle ou négative, vente négative, remise négative ou supérieure au montant de la vente, délai négatif, indicateur de retard différent de 0 ou 1. Aucun contrôle n’a relevé d’anomalie : aucune ligne n’a été rejetée et les 180 519 lignes sont conservées. Ce résultat atteste de la cohérence interne du jeu de données et de la réussite de la conversion des dates. Il ne signifie pas pour autant que toutes les valeurs sont normales : ces contrôles détectent l’impossible, non l’inhabituel. Les pertes supérieures au montant de la vente, valides sur le plan logique mais atypiques, restent à signaler. Le dispositif de rejet est conservé dans le script, afin que tout fichier futur contenant des incohérences soit traité automatiquement, avec conservation du motif de chaque rejet.

In [31]:
#creation des colonnes calculés
# 1. Écart entre le délai réel et le délai prévu
data["ecart_jours"] = data["jours_reels"] - data["jours_prevus"]

# 2. Expédition annulée : 1 = oui, 0 = non
data["expedition_annulee"] = (data["statut_livraison"] == "Shipping canceled").astype(int)

# 3. Livré à temps (à l'heure ou en avance) : 1 = oui, 0 = non
data["livre_a_temps"] = data["statut_livraison"].isin(
    ["Shipping on time", "Advance shipping"]).astype(int)

# 4 et 5. Année et mois de la commande
data["annee_commande"] = data["date_commande"].dt.year
data["mois_commande"] = data["date_commande"].dt.strftime("%Y-%m")

# Arrondi des montants à 2 décimales (sans toucher aux coordonnées)
montants = [c for c in data.select_dtypes(include="float").columns
            if c not in ("latitude", "longitude")]
data[montants] = data[montants].round(2)

print(data.shape)

(180519, 47)

In [32]:
print("Écart moyen (jours)        :", round(data["ecart_jours"].mean(), 2))
print("Expéditions annulées       :", data["expedition_annulee"].sum())
print("Lignes livrées à temps     :", data["livre_a_temps"].sum())

expediees = data[data["expedition_annulee"] == 0]
print("Taux de livraison à temps  :", round(expediees["livre_a_temps"].mean() * 100, 1), "%")
print("Période :", data["mois_commande"].min(), "->", data["mois_commande"].max())

Écart moyen (jours)        : 0.57
Expéditions annulées       : 7754
Lignes livrées à temps     : 73788
Taux de livraison à temps  : 42.7 %
Période : 2015-01 -> 2018-01

Cinq colonnes ont été créées pour préparer le calcul des indicateurs. ecart_jours mesure la différence entre le délai réel et le délai prévu : elle vaut en moyenne 0,57 jour, ce qui confirme que les expéditions prennent un peu plus d’une demi-journée de plus que prévu. expedition_annulee identifie les 7 754 lignes annulées, qui seront exclues des indicateurs de délai puisqu’elles n’ont jamais été livrées. livre_a_temps repère les 73 788 lignes livrées à l’heure ou en avance : rapportées aux 172 765 lignes réellement expédiées, elles donnent un taux de livraison à temps de 42,7 %, ce qui signifie que 57,3 % des expéditions arrivent en retard. Enfin, annee_commande et mois_commande montrent que les données couvrent 37 mois, de janvier 2015 à janvier 2018, période sur laquelle l’évolution des retards pourra être suivie. Ces résultats recoupent exactement ceux du diagnostic, ce qui valide les calculs. Le jeu de données compte désormais 47 colonnes pour 180 519 lignes.

In [33]:
#afficher certaines colonnes uniquement pour les lignes où etat_client contient seulement des chiffres.
masque = data["etat_client"].astype(str).str.isdigit()
data.loc[masque, ["rue_client", "ville_client", "etat_client",
                "code_postal_client", "latitude", "longitude"]]

,rue_client,ville_client,etat_client,code_postal_client,latitude,longitude
35704,Elk Grove,CA,95758,0,39.134159,-123.718552
46440,Elk Grove,CA,95758,0,38.408573,-121.449112
82511,El Monte,CA,91732,0,34.071892,-118.013886

rue_client contient Elk Grove ou El Monte, qui semblent être des noms de villes plutôt que des noms de rues.
ville_client contient CA, l'abréviation de la Californie (California), un État américain.
etat_client contient 95758 ou 91732, des valeurs qui ressemblent à des codes postaux américains.
code_postal_client contient 0, ce qui semble suspect dans ce contexte.
latitude et longitude contiennent des coordonnées géographiques numériques. Elles doivent être vérifiées séparément : leur présence ne suffit pas à confirmer que l'adresse est correcte.

In [34]:
print(data.columns.tolist())

['type_paiement', 'jours_reels', 'jours_prevus', 'benefice_commande', 'ventes_par_client', 'statut_livraison', 'risque_retard', 'categorie_id', 'categorie', 'ville_client', 'pays_client', 'prenom_client', 'nom_client', 'segment_client', 'etat_client', 'rue_client', 'code_postal_client', 'departement_id', 'departement', 'latitude', 'longitude', 'marche', 'ville_livraison', 'pays_livraison', 'commande_client_id', 'date_commande', 'commande_id', 'ligne_produit_id', 'remise', 'taux_remise', 'ligne_id', 'prix_unitaire', 'taux_marge', 'quantite', 'ventes', 'region_livraison', 'etat_livraison', 'statut_commande', 'image_produit', 'produit', 'date_expedition', 'mode_expedition', 'ecart_jours', 'expedition_annulee', 'livre_a_temps', 'annee_commande', 'mois_commande']

In [35]:
#corrigeons ces lignes en déplaçant les valeurs vers les colonnes appropriées
masque = data["etat_client"].astype(str).str.isdigit()

data.loc[masque, "code_postal_client"] = data.loc[masque, "etat_client"].astype(int)
data.loc[masque, "etat_client"] = data.loc[masque, "ville_client"]
data.loc[masque, "ville_client"] = data.loc[masque, "rue_client"]
data.loc[masque, "rue_client"] = "Inconnue"

print("Lignes corrigées :", masque.sum())

Lignes corrigées : 3

In [36]:
data.loc[[35704, 46440, 82511], ["rue_client", "ville_client", "etat_client",
                               "code_postal_client"]]

      rue_client ville_client etat_client  code_postal_client
35704   Inconnue    Elk Grove          CA               95758
46440   Inconnue    Elk Grove          CA               95758
82511   Inconnue     El Monte          CA               91732

In [37]:
print("États numériques restants :", data["etat_client"].astype(str).str.isdigit().sum())
print("Codes postaux à 0 :", (data["code_postal_client"] == 0).sum())

États numériques restants : 0
Codes postaux à 0 : 0

In [ ]:
data.to_csv("DataCoSupplyChainDataset_nettoyees.csv", index=False)

Fichier enregistré : (180519, 47)